language: clojure
lein: 2.7.1
script:
- lein cljfmt check
- lein test
- lein codox
after_success:
- ./add-tmp-remote
- ./push-docs
jdk:
- openjdk7
env:
  global:
    secure: HZ+EfMYAm+UP3iTius0VUs6vmEaLQ/AnpOJ6RHUmprTzU3oAZcXOfWaDUCpcMHkpPUuLVn0w3d73UQEGdcTVWwo1tp8SJroc2Mkq57pveysOPBF1y3zoCROWeMXn+GM5SAJvGa0I8bvOPUaORo47pzl8OfxM7C1BJs3/0/WwiCuCf4tKXyc81G43amLuVHIC6mRC8Yz0j+dLYGseMtBjBtocmwKUkolbI+Rca6V0ANY6+ViSzPiag0/AgMZkcC59d2pnZd4T7RG2ESog+J0NiAL800alpD2Q+UIK4GRp+4FxWEeMct/zV878wGZa215t0M1O06E869b+aRCoQql9P42L4xrWKN4smykCZDbPGhoDzm0pml4Ah9VG0Kc6DojVJvTjTcCJzZqKO3WyBVDVpoZD6rdjxi1eAHO8j0uARLZT06G3L0IVtGxv+0SSyL3j+/uW3PUhjGRyuGAWjXaujg2RTib0t1e/Q+GM8ix8BLW2vUpSfrp6QVKJdE9EVtkvw6w8anRL2VW3Ip2gcgG34JwqwDPjdiC52iyVNthd/Sxi6nSInLILQLOOhwUMQV+4G6f1UZuTa6nQPNULXEx+fI1+ShwMvn53NoJnEvXZ9sdCx3IDKstck1q0BdRx7zXEYuG6d5QiB/gG24Ay2vDAUnCaP7/79kPtU3Sx56X2+tY=
